# Generated by Django 5.0.4 on 2024-05-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MCQS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sub_topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQS.subtopic')),
            ],
        ),
    ]
