# Generated by Django 5.0.4 on 2024-05-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUTORMODE', '0002_note_user_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
    ]
